# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-11-21 12:24:18
"""
import arcpy

# 'def' is where we can define a reuseable function
def Flooding():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    
    arcpy.env.overwriteOutput = True # default was Fasle when we exported this model

    # \n means a new line \t means a new tab, so the backslash ahs a Python meaning
    # floodzones = r"C:\PythonPro\Ex03\Study.gdb\floodzones" # r means 'raw' i.e. plain old backlashes
    floodzones = r".\Study.gdb\floodzones" # we can use relative paths
    basin = "C:\\PythonPro\\Ex03\\Study.gdb\\basin" # \\ means insert a backslash

    # Process: Clip (Clip) (analysis)
    # we can use forward slashes instead
    floodzones_Clip = "C:/Users/rb17/AppData/Local/Temp/ArcGISProTemp14204/654a171f-e7d1-4d49-af7c-6010629b6b77\\Default.gdb\\floodzones_Clip"
    arcpy.analysis.Clip(in_features=floodzones, clip_features=basin, out_feature_class=floodzones_Clip, cluster_tolerance="")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\rb17\AppData\Local\Temp\ArcGISProTemp14204\654a171f-e7d1-4d49-af7c-6010629b6b77\Default.gdb", workspace=r"C:\Users\rb17\AppData\Local\Temp\ArcGISProTemp14204\654a171f-e7d1-4d49-af7c-6010629b6b77\Default.gdb"):
        Flooding()

    # back at this block

# back at top level (no block indentation)
